' Gambas module file


Public Function MqttPublish(sTopic As String, sMessage As String) As Boolean
Dim rs As Boolean = True
Dim sBrokerIp As String = "192.168.178.2"
Dim sOutput As String

  Exec ["mosquitto_pub", "-h", sBrokerIp, "-t", sTopic, "-m", sMessage] To sOutput

  If Error Then
    Message.Error(("Error when running mosquitto_pub"))
    Return False
  Endif
  Return rs

End


Public Function MqttSwitchSprinkler(iNumber As Integer, bOnOff As Boolean, iDuration As Integer) As Boolean
Dim rs As Boolean = True
' Example command:
' mosquitto_pub -h 192.168.1.2 -t tcs/sprink/in -m "{ \"number\": 1, \"dauer\": 600, \"action\": \"START\" }"

Dim sTopic As String = "tcs/sprink/in"
Dim sMessage As String = "{ \"number\": " & iNumber &
                         ", \"dauer\": " & iDuration & 
                         ", \"action\": \"" & IIf(bOnOff, "START", "STOP") &
                         "\"}"

rs = MqttPublish(sTopic, sMessage)

Return rs

End

Public Function MqttSwitchLight(bOnOff As Boolean) As Boolean
Dim rs As Boolean = True
' Example command:
' mosquitto_pub -h 192.168.1.2 -t tcs/sprink/in -m "{ \"number\": 1, \"dauer\": 600, \"action\": \"START\" }"

Dim sTopic As String = "tcs/light/in"
Dim sMessage As String = IIf(bOnOff, "true", "false")

rs = MqttPublish(sTopic, sMessage)

Return rs

End

